// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwp4Y3QK3ATX97uJIm0QOYeUS-L9me_-o',
    appId: '1:385497871982:web:956651776547838bb2587f',
    messagingSenderId: '385497871982',
    projectId: 'quest-227e4',
    authDomain: 'quest-227e4.firebaseapp.com',
    storageBucket: 'quest-227e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6sBb5MdBKm41h9u9zO-g-yya0dzh52M',
    appId: '1:385497871982:android:764b1b2cc9fd201db2587f',
    messagingSenderId: '385497871982',
    projectId: 'quest-227e4',
    storageBucket: 'quest-227e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2AxK2hqF5qgBnKNSRwPmMVHCF_lGyk4',
    appId: '1:385497871982:ios:67f1b2da3927f435b2587f',
    messagingSenderId: '385497871982',
    projectId: 'quest-227e4',
    storageBucket: 'quest-227e4.firebasestorage.app',
    iosBundleId: 'com.example.notesquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2AxK2hqF5qgBnKNSRwPmMVHCF_lGyk4',
    appId: '1:385497871982:ios:67f1b2da3927f435b2587f',
    messagingSenderId: '385497871982',
    projectId: 'quest-227e4',
    storageBucket: 'quest-227e4.firebasestorage.app',
    iosBundleId: 'com.example.notesquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwp4Y3QK3ATX97uJIm0QOYeUS-L9me_-o',
    appId: '1:385497871982:web:41f9a4fabfbf3844b2587f',
    messagingSenderId: '385497871982',
    projectId: 'quest-227e4',
    authDomain: 'quest-227e4.firebaseapp.com',
    storageBucket: 'quest-227e4.firebasestorage.app',
  );
}
